name: React Native Expo CI

on:
  push:
    branches:
      - main

jobs:
  expo-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        echo "Installing project dependencies..."
        npm install
        echo "Installing Expo CLI globally..."
        npm install -g expo-cli

    - name: Install expo-updates
      run: |
        echo "Ensuring expo-updates is installed..."
        npm install expo-updates

    - name: Login to Expo
      run: |
        echo "Logging in to Expo..."
        expo login --non-interactive -u ${{ secrets.EXPO_CLI_USERNAME }} -p ${{ secrets.EXPO_CLI_PASSWORD }}

    - name: Publish to Expo
      run: |
        echo "Publishing project to Expo..."
        expo publish
      env:
        CI: true
